### ISSUE TITLE
Cannot open 3.16Gb file...

### ISSUE THREAD

**Issue by jimlynnjulian** [dlwhittenbury/MySQL_IMDb_Project#5]
Ran the program 'imdb_converter.py' and everything worked up to 'principals'. Then the program crashed with the following error:

"Reading title.principals.tsv ...

Traceback (most recent call last):
  File "C:\Temp\Movie databases\MySQL_IMDb_Project-master24\imdb_converter2.py", line 258, in <module>
    title_principals = pd.read_csv(os.path.join(data_path,'title.principals.tsv'),sep='\t',na_values='\\N')
  File "C:\Python310\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 581, in _read
    return parser.read(nrows)
  File "C:\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1270, in read
    df = DataFrame(col_dict, columns=columns, index=index)
  File "C:\Python310\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Python310\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Python310\lib\site-packages\pandas\core\internals\construction.py", line 156, in arrays_to_mgr
    return create_block_manager_from_column_arrays(
  File "C:\Python310\lib\site-packages\pandas\core\internals\managers.py", line 1959, in create_block_manager_from_column_arrays
    mgr._consolidate_inplace()
  File "C:\Python310\lib\site-packages\pandas\core\internals\managers.py", line 1685, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "C:\Python310\lib\site-packages\pandas\core\internals\managers.py", line 2084, in _consolidate
    merged_blocks = _merge_blocks(
  File "C:\Python310\lib\site-packages\pandas\core\internals\managers.py", line 2111, in _merge_blocks
    new_values = np.vstack([b.values for b in blocks])  # type: ignore[misc]
  File "<__array_function__ internals>", line 180, in vstack
  File "C:\Python310\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.19 GiB for an array with shape (5, 85703817) and data type object"

**Comment by jimlynnjulian** [comment]
Moved software and data to a newer laptop.
